# Generated by Django 6.1 on 2026-08-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('cart', '0003_alter_place_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_order',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
    ]
