# Generated by Django 6.1 on 2026-08-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_place_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='products',
        ),
    ]
